name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: write  # Needed to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies 📦
        run: npm install

      - name: Build site 🏗️
        run: npm run generate

      - name: Deploy 🚀
        run: npm run deploy
        env:
          GIT_USER: github-actions
          GIT_EMAIL: github-actions@github.com